In [1]:
import torch

# Tensors

Tensor is a number, vector, matrix or n dimensional array

In [3]:
t = torch.tensor(1)

In [4]:
t

tensor(1)

In [6]:
type(t)

torch.Tensor

In [9]:
tt = torch.tensor([1,2,3])
tt

tensor([1, 2, 3])

In [8]:
type(tt)

torch.Tensor

Define multi dimensional tensors in list of lists with each list having same dimension as the first list\

In [11]:
ttt = torch.tensor([[1,2,3],[4.0,5.6,7.9]])
ttt

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.6000, 7.9000]])

In [12]:
type(ttt)

torch.Tensor

## To find shape of tensor

In [13]:
t.shape

torch.Size([])

In [14]:
tt.shape

torch.Size([3])

In [15]:
ttt.shape

torch.Size([2, 3])

# Tensor Operations and Gradients

To combine tensors using regular arthimetic operators in python

In [40]:
t1 = torch.tensor(3.)
t2 = torch.tensor(2., requires_grad=True)
t3 = torch.tensor(1., requires_grad=True)
t4 = torch.tensor(4., requires_grad=True)

In [33]:
t1*t2*t3

tensor(6., grad_fn=<MulBackward0>)

In [34]:
t1+t2*t3

tensor(5., grad_fn=<AddBackward0>)

In [35]:
t1-t2-t3

tensor(0., grad_fn=<SubBackward0>)

In [36]:
t1/t2/t3

tensor(1.5000, grad_fn=<DivBackward0>)

## Sometimes we may require to calculate derrivative of tensors, then we can use the property requires_grad=True

Pytorch backward used calculus to find the derivatives

In [41]:
l = t1 + t2 + t3*t4

In [42]:
l.backward()

To get derivative of variable with respect to another, compute grad

In [44]:
print('dl/dt1', t1.grad)
print('dl/dt2', t2.grad)
print('dl/dt3', t3.grad)
print('dl/dt4', t4.grad)

dl/dt1 None
dl/dt2 tensor(1.)
dl/dt3 tensor(4.)
dl/dt4 tensor(1.)


# To use with Numpy

In [45]:
import numpy as np

In [47]:
n = np.array([[1,2],[3,4]])

from_numpy does not create copy of the data where tensor creates a copy of the data

In [48]:
tn = torch.from_numpy(n)

In [52]:
tn1 = torch.tensor(n)

In [53]:
n.dtype, tn.dtype, tn1.dtype

(dtype('int32'), torch.int32, torch.int32)

In [56]:
ntn = tn.numpy()
ntn

array([[1, 2],
       [3, 4]])

In [57]:
type(ntn)

numpy.ndarray